//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitShift_FirstData_SavedCard_o
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int BillingAddress_Id { get; set; }
        public string CardholderName { get; set; }
        public string Token { get; set; }
        public int ExpireMonth { get; set; }
        public int ExpireYear { get; set; }
        public string CardType { get; set; }
    }
}
