//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulfillmentCalDay
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
