//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLCode
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string GlCodeName { get; set; }
        public Nullable<int> GlCodeTypeId { get; set; }
    }
}
