//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_GLSpecificationAttribute_Mapping
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int AttributeTypeId { get; set; }
        public int GLSpecificationAttributeOptionId { get; set; }
        public string CustomValue { get; set; }
    
        public virtual GLSpecificationAttributeOption GLSpecificationAttributeOption { get; set; }
        public virtual Product Product { get; set; }
    }
}
