//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTax
    {
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string SessionId { get; set; }
        public int Id { get; set; }
        public Nullable<int> GlCodeId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string TaxCode { get; set; }
    }
}
