//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_SalesJournal
    {
        public int ID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> OrderItemID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SAPDocumentNumber { get; set; }
        public Nullable<int> SAPCompanyCode { get; set; }
        public Nullable<int> SAPFiscalYear { get; set; }
        public Nullable<System.DateTime> SAPPostingDate { get; set; }
        public Nullable<System.DateTime> SAPEntryDate { get; set; }
        public string SAPDocumentType { get; set; }
        public string CostCenterNumber { get; set; }
        public Nullable<System.DateTime> DateOfTransaction { get; set; }
        public string ProductGL { get; set; }
        public Nullable<int> ProductAmount { get; set; }
        public Nullable<int> CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerStreetAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerPostalCode { get; set; }
        public string CustomerCountry { get; set; }
        public string ShipToName { get; set; }
        public string ShipToStreetAddress { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToJurisdiction { get; set; }
        public string ShipFromName { get; set; }
        public string ShipFromStreetAddress { get; set; }
        public string ShipFromCity { get; set; }
        public string ShipFromPostalCode { get; set; }
        public string ShipFromCountry { get; set; }
        public string MasterProduct { get; set; }
        public string LocalProduct { get; set; }
        public Nullable<bool> IsProductTaxable { get; set; }
        public Nullable<decimal> TaxAmountImposed { get; set; }
        public Nullable<decimal> NonTexableAmount { get; set; }
        public Nullable<bool> IsExported { get; set; }
        public string ShipFromState { get; set; }
    }
}
