//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPOrderProcess
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public int OrderItemId { get; set; }
        public int StatusId { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsBundle { get; set; }
    }
}
