//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int ShoppingCartTypeId { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public string AttributesXml { get; set; }
        public decimal CustomerEnteredPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> RentalStartDateUtc { get; set; }
        public Nullable<System.DateTime> RentalEndDateUtc { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
        public Nullable<System.DateTime> RequestedFullfilmentDateTime { get; set; }
        public Nullable<int> SelectedWarehouseId { get; set; }
        public string SelectedShippingMethodName { get; set; }
        public string SelectedShippingRateComputationMethodSystemName { get; set; }
        public Nullable<bool> IsReservation { get; set; }
        public string ReservedTimeSlot { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<bool> IsTieredShippingEnabled { get; set; }
        public Nullable<bool> IsContractShippingEnabled { get; set; }
        public Nullable<bool> IsInterOfficeDeliveryEnabled { get; set; }
        public Nullable<decimal> FlatShipping { get; set; }
        public string RCNumber { get; set; }
        public string MailStopAddress { get; set; }
        public Nullable<bool> IsFirstCartItem { get; set; }
        public Nullable<bool> IsBundleProduct { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
