//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCommission
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public int StoreId { get; set; }
        public decimal Commission { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
