//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxResponseStorage
    {
        public int CustomerID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ProductID { get; set; }
        public int TypeOfCall { get; set; }
        public string XMlResponse { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
    }
}
