//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commuter1
    {
        public string StudentEmplID { get; set; }
        public string StudentLastName { get; set; }
        public string StudentFirstName { get; set; }
        public Nullable<int> StoreId { get; set; }
        public int Id { get; set; }
    }
}
