//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLSpecificationAttributeOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLSpecificationAttributeOption()
        {
            this.Product_GLSpecificationAttribute_Mapping = new HashSet<Product_GLSpecificationAttribute_Mapping>();
        }
    
        public int Id { get; set; }
        public int GLSpecificationAttributeId { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public string Value { get; set; }
        public string Amount { get; set; }
        public Nullable<bool> IsDeferred { get; set; }
    
        public virtual GLSpecificationAttribute GLSpecificationAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_GLSpecificationAttribute_Mapping> Product_GLSpecificationAttribute_Mapping { get; set; }
    }
}
