//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem_fulfillmentdate_bkp_070219
    {
        public int id { get; set; }
        public Nullable<System.DateTime> FulfillmentDateTime { get; set; }
    }
}
