//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.Donations = new HashSet<Donation>();
            this.GiftCards = new HashSet<GiftCard>();
            this.MealPlans = new HashSet<MealPlan>();
        }
    
        public int Id { get; set; }
        public System.Guid OrderItemGuid { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPriceInclTax { get; set; }
        public decimal UnitPriceExclTax { get; set; }
        public decimal PriceInclTax { get; set; }
        public decimal PriceExclTax { get; set; }
        public decimal DiscountAmountInclTax { get; set; }
        public decimal DiscountAmountExclTax { get; set; }
        public decimal OriginalProductCost { get; set; }
        public string AttributeDescription { get; set; }
        public string AttributesXml { get; set; }
        public int DownloadCount { get; set; }
        public bool IsDownloadActivated { get; set; }
        public Nullable<int> LicenseDownloadId { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public Nullable<System.DateTime> RentalStartDateUtc { get; set; }
        public Nullable<System.DateTime> RentalEndDateUtc { get; set; }
        public Nullable<decimal> StoreCommission { get; set; }
        public Nullable<int> SelectedFulfillmentWarehouseId { get; set; }
        public Nullable<System.DateTime> RequestedFulfillmentDateTime { get; set; }
        public Nullable<System.DateTime> FulfillmentDateTime { get; set; }
        public string SelectedShippingMethodName { get; set; }
        public string ShippingMethod { get; set; }
        public string ShippingRateComputationMethodSystemName { get; set; }
        public string SelectedShippingRateComputationMethodSystemName { get; set; }
        public Nullable<int> Status { get; set; }
        public decimal DeliveryAmountExclTax { get; set; }
        public Nullable<decimal> GlcodeAmount1 { get; set; }
        public Nullable<decimal> GlcodeAmount2 { get; set; }
        public Nullable<decimal> GlcodeAmount3 { get; set; }
        public Nullable<decimal> TaxAmount1 { get; set; }
        public Nullable<decimal> TaxAmount2 { get; set; }
        public Nullable<decimal> TaxAmount3 { get; set; }
        public Nullable<decimal> TotalRefundedAmount { get; set; }
        public Nullable<bool> IsPartialRefund { get; set; }
        public Nullable<decimal> RefundedTaxAmount1 { get; set; }
        public Nullable<decimal> RefundedTaxAmount2 { get; set; }
        public Nullable<decimal> RefundedTaxAmount3 { get; set; }
        public Nullable<decimal> RefundedGlAmount1 { get; set; }
        public Nullable<decimal> RefundedGlAmount2 { get; set; }
        public Nullable<decimal> RefundedGlAmount3 { get; set; }
        public string GLCodeName1 { get; set; }
        public string GLCodeName2 { get; set; }
        public string GLCodeName3 { get; set; }
        public string TaxName1 { get; set; }
        public string TaxName2 { get; set; }
        public string TaxName3 { get; set; }
        public Nullable<bool> IsDeliveryPickUp { get; set; }
        public Nullable<bool> IsShipping { get; set; }
        public Nullable<decimal> DeliveryPickupFee { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> PartialRefundOrderAmount { get; set; }
        public Nullable<bool> IsFullRefund { get; set; }
        public Nullable<decimal> DeliveryPickupAmount { get; set; }
        public Nullable<decimal> ShippingAmount { get; set; }
        public Nullable<decimal> DelliveryTax { get; set; }
        public Nullable<decimal> ShippingTax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCard> GiftCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealPlan> MealPlans { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
