//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreExtKey { get; set; }
        public string StoreLegalEntity { get; set; }
        public string StoreState { get; set; }
        public string StoreZip { get; set; }
        public string StoreCity { get; set; }
        public string ShipFromCity { get; set; }
        public string ShipFromState { get; set; }
        public string ShipFromZip { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public Nullable<bool> IsMealPlan { get; set; }
        public Nullable<bool> IsDonation { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public string VertexTaxAreaId { get; set; }
        public string ProductName { get; set; }
    }
}
