//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingTaxCategory
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> TaxCategoryId { get; set; }
        public Nullable<int> GLCode1Id { get; set; }
        public Nullable<decimal> GlCode1Amount { get; set; }
        public Nullable<int> GlCode2Id { get; set; }
        public Nullable<decimal> GLCode2Amount { get; set; }
        public Nullable<int> DeliveryGlId { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> GlCode3Id { get; set; }
        public Nullable<decimal> GlCode3Amount { get; set; }
        public Nullable<int> MasterProductId { get; set; }
    }
}
