//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Email_Mapping
    {
        public int Id { get; set; }
        public int EmailTypeId { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual Store Store { get; set; }
    }
}
