//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackFillForReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.Product_PickupWarehouses_Mapping = new HashSet<Product_PickupWarehouses_Mapping>();
            this.ProductWarehouseInventories = new HashSet<ProductWarehouseInventory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AdminComment { get; set; }
        public int AddressId { get; set; }
        public bool IsMaster { get; set; }
        public int MasterId { get; set; }
        public bool LimitedToStores { get; set; }
        public string Email { get; set; }
        public Nullable<int> LeadTimeDays { get; set; }
        public Nullable<int> LeadTimeHours { get; set; }
        public Nullable<int> LeadTimeMinutes { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public string DeliveryCloseTime { get; set; }
        public string DeliveryOpenTime { get; set; }
        public string PickupCloseTime { get; set; }
        public string PickupOpenTime { get; set; }
        public bool IsDelivery { get; set; }
        public bool IsPickup { get; set; }
        public bool AllowPickupTime { get; set; }
        public bool AllowDeliveryTime { get; set; }
        public string DeliveryOpenTimeSun { get; set; }
        public string DeliveryCloseTimeSun { get; set; }
        public string DeliveryOpenTimeMon { get; set; }
        public string DeliveryCloseTimeMon { get; set; }
        public string DeliveryOpenTimeTues { get; set; }
        public string DeliveryCloseTimeTues { get; set; }
        public string DeliveryOpenTimeWeds { get; set; }
        public string DeliveryCloseTimeWeds { get; set; }
        public string DeliveryOpenTimeThurs { get; set; }
        public string DeliveryCloseTimeThurs { get; set; }
        public string DeliveryOpenTimeFri { get; set; }
        public string DeliveryCloseTimeFri { get; set; }
        public string DeliveryOpenTimeSat { get; set; }
        public string DeliveryCloseTimeSat { get; set; }
        public string PickupOpenTimeSun { get; set; }
        public string PickupCloseTimeSun { get; set; }
        public string PickupOpenTimeMon { get; set; }
        public string PickupCloseTimeMon { get; set; }
        public string PickupOpenTimeTues { get; set; }
        public string PickupCloseTimeTues { get; set; }
        public string PickupOpenTimeWeds { get; set; }
        public string PickupCloseTimeWeds { get; set; }
        public string PickupOpenTimeThurs { get; set; }
        public string PickupCloseTimeThurs { get; set; }
        public string PickupOpenTimeFri { get; set; }
        public string PickupCloseTimeFri { get; set; }
        public string PickupOpenTimeSat { get; set; }
        public string PickupCloseTimeSat { get; set; }
        public string KitchenPrinterURL { get; set; }
        public Nullable<decimal> DeliveryFee { get; set; }
        public Nullable<decimal> PickupFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_PickupWarehouses_Mapping> Product_PickupWarehouses_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWarehouseInventory> ProductWarehouseInventories { get; set; }
    }
}
