//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool SslEnabled { get; set; }
        public string SecureUrl { get; set; }
        public string Hosts { get; set; }
        public int DefaultLanguageId { get; set; }
        public int DisplayOrder { get; set; }
        public string CompanyName { get; set; }
      
        public string CompanyAddress { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyCity { get; set; } 
        public string CompanyZipPostalCode { get; set; }
        public int CompanyStateProvinceId { get; set; }
        public int CompanyCountryId { get; set; }
        
        
        public string CompanyPhoneNumber { get; set; }
        public string CompanyVat { get; set; }
        public string TimeZoneInfoId { get; set; }
        public string ExtKey { get; set; }
        public string DiningSiteURL { get; set; }
    }
}
